package core

const (
	HDR_ACCEPT             = iota // Accept ,
	HDR_ACCEPTDISPOSITION         // Accept-Disposition
	HDR_ACCEPTLANGUAGE            // Accept-Language ,
	HDR_ALLOW                     // Allow ,
	HDR_AUTHORIZATION             // Authorization ,
	HDR_BYTE_RANGE                // MSRP Byte-Range ,
	HDR_CALLID                    // Call-Id ,	// i
	HDR_CALL_INFO                 // Call-Info ,
	HDR_CONTACT                   // Contact , 	// m
	HDR_CONTENTDISPOSITION        // Content-Disposition
	HDR_CONTENTENCODING           // Content-Encoding , // e
	HDR_CONTENTLENGTH             // Content-Length ,   // l
	HDR_CONTENTTYPE               // Content-Type ,     // c
	HDR_CSEQ                      // CSeq ,
	HDR_DIVERSION                 // Diversion ,
	HDR_EOH                       // Some other ,
	HDR_EVENT                     // Event ,
	HDR_EXPIRES                   // Expires ,
	HDR_FAILURE_REPORT            // MSRP Failure-Report ,
	HDR_FEATURE_CAPS              // Feature-Caps ,
	HDR_FROM                      // From , // f
	HDR_FROM_PATH                 // MSRP From-Path ,
	HDR_MAXFORWARDS               // MaxForwards ,
	HDR_MESSAGE_ID                // MSRP Message-ID ,
	HDR_MIN_EXPIRES               // Min-Expires ,
	HDR_MIN_SE                    // Min-SE ,
	HDR_ORGANIZATION              // Organization ,
	HDR_OTHER                     // Some other ,
	HDR_PAI                       // P-Asserted-Identity ,
	HDR_PATH                      // Path
	HDR_PPI                       // P-Preferred-Identity ,
	HDR_PRIORITY                  // Priority ,
	HDR_PRIVACY                   // Privacy ,
	HDR_PROXYAUTH                 // Proxy-Authorization
	HDR_PROXYREQUIRE              // Proxy-Require ,
	HDR_PROXY_AUTHENTICATE        // Proxy-Authenticate ,
	HDR_RECORDROUTE               // Record-Route ,
	HDR_REFER_TO                  // Refer-To
	HDR_REPLACES                  // Replaces ,
	HDR_RETRY_AFTER               // Retry-After ,
	HDR_ROUTE                     // Route ,
	HDR_RPID                      // Remote-Party-ID ,
	HDR_SECURITY_CLIENT           // sec-agree RFC3329 Security-Client ,
	HDR_SECURITY_SERVER           // sec-agree RFC3329 Security-Server ,
	HDR_SECURITY_VERIFY           // sec-agree RFC3329 Security-Verify ,
	HDR_SESSION_EXPIRES           // Session-Expires ,
	HDR_STATUS                    // MSRP Status ,
	HDR_SUBJECT                   // Subject , // s
	HDR_SUCCESS_REPORT            // MSRP Success-Report ,
	HDR_SUPPORTED                 // Supported  , // k
	HDR_TO                        // To ,         // t
	HDR_TO_PATH                   // MSRP To-Path ,
	HDR_UNSUPPORTED               // Unsupported ,
	HDR_USERAGENT                 // User-Agent ,
	HDR_USE_PATH                  // MSRP Use-Path ,
	HDR_VIA                       // Via , // v
	HDR_WWW_AUTHENTICATE          // WWW-Authenticate ,
)

var hdrType2Name = map[int]string{
	HDR_ACCEPT:             "Accept",
	HDR_ACCEPTDISPOSITION:  "Accept-Disposition",
	HDR_ACCEPTLANGUAGE:     "Accept-Language",
	HDR_ALLOW:              "Allow",
	HDR_AUTHORIZATION:      "Authorization",
	HDR_BYTE_RANGE:         "MSRP Byte-Range",
	HDR_CALLID:             "Call-Id",
	HDR_CALL_INFO:          "Call-Info",
	HDR_CONTACT:            "Contact",
	HDR_CONTENTDISPOSITION: "Content-Disposition",
	HDR_CONTENTENCODING:    "Content-Encoding",
	HDR_CONTENTLENGTH:      "Content-Length",
	HDR_CONTENTTYPE:        "Content-Type",
	HDR_CSEQ:               "CSeq",
	HDR_DIVERSION:          "Diversion",
	HDR_EOH:                "Some other",
	HDR_EVENT:              "Event",
	HDR_EXPIRES:            "Expires",
	HDR_FAILURE_REPORT:     "MSRP Failure-Report",
	HDR_FEATURE_CAPS:       "Feature-Caps",
	HDR_FROM:               "From",
	HDR_FROM_PATH:          "MSRP From-Path",
	HDR_MAXFORWARDS:        "MaxForwards",
	HDR_MESSAGE_ID:         "MSRP Message-ID",
	HDR_MIN_EXPIRES:        "Min-Expires",
	HDR_MIN_SE:             "Min-SE",
	HDR_ORGANIZATION:       "Organization",
	HDR_OTHER:              "Some other",
	HDR_PAI:                "P-Asserted-Identity",
	HDR_PATH:               "Path",
	HDR_PPI:                "P-Preferred-Identity",
	HDR_PRIORITY:           "Priority",
	HDR_PRIVACY:            "Privacy",
	HDR_PROXYAUTH:          "Proxy-Authorization",
	HDR_PROXYREQUIRE:       "Proxy-Require",
	HDR_PROXY_AUTHENTICATE: "Proxy-Authenticate",
	HDR_RECORDROUTE:        "Record-Route",
	HDR_REFER_TO:           "Refer-To",
	HDR_REPLACES:           "Replaces",
	HDR_RETRY_AFTER:        "Retry-After",
	HDR_ROUTE:              "Route",
	HDR_RPID:               "Remote-Party-ID",
	HDR_SECURITY_CLIENT:    "sec-agree RFC3329 Security-Client",
	HDR_SECURITY_SERVER:    "sec-agree RFC3329 Security-Server",
	HDR_SECURITY_VERIFY:    "sec-agree RFC3329 Security-Verify",
	HDR_SESSION_EXPIRES:    "Session-Expires",
	HDR_STATUS:             "MSRP Status",
	HDR_SUBJECT:            "Subject",
	HDR_SUCCESS_REPORT:     "MSRP Success-Report",
	HDR_SUPPORTED:          "Supported",
	HDR_USERAGENT:          "User-Agent",
	HDR_USE_PATH:           "MSRP Use-Path",
	HDR_VIA:                "Via",
	HDR_WWW_AUTHENTICATE:   "WWW-Authenticate",
}

var hdrType2ShortName = map[int]string{
	HDR_FROM:          "F",
	HDR_CALLID:        "I",
	HDR_SUPPORTED:     "K",
	HDR_CONTENTLENGTH: "L",
	HDR_CONTACT:       "M",
	HDR_SUBJECT:       "S",
	HDR_VIA:           "V",
}

var hdrName2Type = map[string]int{
	"Accept-Disposition":   HDR_ACCEPTDISPOSITION,
	"accept-disposition":   HDR_ACCEPTDISPOSITION,
	"Accept-Language":      HDR_ACCEPTLANGUAGE,
	"accept-language":      HDR_ACCEPTLANGUAGE,
	"Accept":               HDR_ACCEPT,
	"accept":               HDR_ACCEPT,
	"Allow":                HDR_ALLOW,
	"allow":                HDR_ALLOW,
	"Authorization":        HDR_AUTHORIZATION,
	"authorization":        HDR_AUTHORIZATION,
	"Byte-Range":           HDR_BYTE_RANGE,
	"byte-range":           HDR_BYTE_RANGE,
	"Call-ID":              HDR_CALLID,
	"call-id":              HDR_CALLID,
	"Call-Info":            HDR_CALL_INFO,
	"call-info":            HDR_CALL_INFO,
	"Contact":              HDR_CONTACT,
	"contact":              HDR_CONTACT,
	"Content-Disposition":  HDR_CONTENTDISPOSITION,
	"content-disposition":  HDR_CONTENTDISPOSITION,
	"Content-Length":       HDR_CONTENTLENGTH,
	"content-length":       HDR_CONTENTLENGTH,
	"Content-Type":         HDR_CONTENTTYPE,
	"content-type":         HDR_CONTENTTYPE,
	"CSeq":                 HDR_CSEQ,
	"cseq":                 HDR_CSEQ,
	"Diversion":            HDR_DIVERSION,
	"diversion":            HDR_DIVERSION,
	"Event":                HDR_EVENT,
	"event":                HDR_EVENT,
	"Expires":              HDR_EXPIRES,
	"expires":              HDR_EXPIRES,
	"F":                    HDR_FROM,
	"f":                    HDR_FROM,
	"Failure-Report":       HDR_FAILURE_REPORT,
	"failure-report":       HDR_FAILURE_REPORT,
	"Feature-Caps":         HDR_FEATURE_CAPS,
	"feature-caps":         HDR_FEATURE_CAPS,
	"From-Path":            HDR_FROM_PATH,
	"from-path":            HDR_FROM_PATH,
	"From":                 HDR_FROM,
	"from":                 HDR_FROM,
	"i":                    HDR_CALLID,
	"I":                    HDR_CALLID,
	"K":                    HDR_SUPPORTED,
	"k":                    HDR_SUPPORTED,
	"L":                    HDR_CONTENTLENGTH,
	"l":                    HDR_CONTENTLENGTH,
	"M":                    HDR_CONTACT,
	"m":                    HDR_CONTACT,
	"Max-Forwards":         HDR_MAXFORWARDS,
	"max-forwards":         HDR_MAXFORWARDS,
	"Message-ID":           HDR_MESSAGE_ID,
	"message-id":           HDR_MESSAGE_ID,
	"Min-Expires":          HDR_MIN_EXPIRES,
	"min-expires":          HDR_MIN_EXPIRES,
	"Min-SE":               HDR_MIN_SE,
	"min-se":               HDR_MIN_SE,
	"Organization":         HDR_ORGANIZATION,
	"organization":         HDR_ORGANIZATION,
	"P-Asserted-Identity":  HDR_PAI,
	"p-asserted-identity":  HDR_PAI,
	"P-Preferred-Identity": HDR_PPI,
	"p-preferred-identity": HDR_PPI,
	"Path":                 HDR_PATH,
	"path":                 HDR_PATH,
	"Priority":             HDR_PRIORITY,
	"priority":             HDR_PRIORITY,
	"Privacy":              HDR_PRIVACY,
	"privacy":              HDR_PRIVACY,
	"Proxy-Authenticate":   HDR_PROXY_AUTHENTICATE,
	"proxy-authenticate":   HDR_PROXY_AUTHENTICATE,
	"Proxy-Authorization":  HDR_PROXYAUTH,
	"proxy-authorization":  HDR_PROXYAUTH,
	"Proxy-Require":        HDR_PROXYREQUIRE,
	"proxy-require":        HDR_PROXYREQUIRE,
	"Record-Route":         HDR_RECORDROUTE,
	"record-route":         HDR_RECORDROUTE,
	"Refer-To":             HDR_REFER_TO,
	"refer-to":             HDR_REFER_TO,
	"Remote-Party-ID":      HDR_RPID,
	"remote-party-id":      HDR_RPID,
	"Replaces":             HDR_REPLACES,
	"replaces":             HDR_REPLACES,
	"Retry-After":          HDR_RETRY_AFTER,
	"retry-after":          HDR_RETRY_AFTER,
	"Route":                HDR_ROUTE,
	"route":                HDR_ROUTE,
	"S":                    HDR_SUBJECT,
	"s":                    HDR_SUBJECT,
	"Security-Client":      HDR_SECURITY_CLIENT,
	"security-client":      HDR_SECURITY_CLIENT,
	"Security-Server":      HDR_SECURITY_SERVER,
	"security-server":      HDR_SECURITY_SERVER,
	"Security-Verify":      HDR_SECURITY_VERIFY,
	"security-verify":      HDR_SECURITY_VERIFY,
	"Session-Expires":      HDR_SESSION_EXPIRES,
	"session-expires":      HDR_SESSION_EXPIRES,
	"Status":               HDR_STATUS,
	"status":               HDR_STATUS,
	"Subject":              HDR_SUBJECT,
	"subject":              HDR_SUBJECT,
	"Success-Report":       HDR_SUCCESS_REPORT,
	"success-report":       HDR_SUCCESS_REPORT,
	"Supported":            HDR_SUPPORTED,
	"supported":            HDR_SUPPORTED,
	"To-Path":              HDR_TO_PATH,
	"to-path":              HDR_TO_PATH,
	"To":                   HDR_TO,
	"to":                   HDR_TO,
	"Unsupported":          HDR_UNSUPPORTED,
	"unsupported":          HDR_UNSUPPORTED,
	"Use-Path":             HDR_USE_PATH,
	"use-path":             HDR_USE_PATH,
	"User-Agent":           HDR_USERAGENT,
	"user-agent":           HDR_USERAGENT,
	"V":                    HDR_VIA,
	"v":                    HDR_VIA,
	"Via":                  HDR_VIA,
	"via":                  HDR_VIA,
	"WWW-Authenticate":     HDR_WWW_AUTHENTICATE,
	"www-authenticate":     HDR_WWW_AUTHENTICATE,
}

func GetHeaderType(hdr []byte) int {
	return hdrName2Type[string(hdr)]
}
